// lsdl_adder4 — 4-bit dual-rail pipelined ripple-carry adder
// in LSDL cells. Generated by gen_lsdl_adder.py — do not edit.
//
// Clocking: odd stages on c1, even stages on c2 (180 deg apart);
// one half period per stage transfer.
// Cells: 92 (72 inv, 20 aoi22)
// Output latency (half-cycles): sum[0]@2, sum[1]@4, sum[2]@6, sum[3]@8, cout@8
`timescale 1ns/1ps
module lsdl_adder4 (
    input  c1,
    input  c2,
    input  [3:0] a,
    input  [3:0] an,
    input  [3:0] b,
    input  [3:0] bn,
    input  cin,
    input  cinn,
    output [3:0] sum,
    output cout,
    output coutn
);

    wire p_a0_s1;
    wire q_a0_s1;
    wire p_a1_s1;
    wire p_a1_s2;
    wire p_a1_s3;
    wire q_a1_s1;
    wire q_a1_s2;
    wire q_a1_s3;
    wire p_a2_s1;
    wire p_a2_s2;
    wire p_a2_s3;
    wire p_a2_s4;
    wire p_a2_s5;
    wire q_a2_s1;
    wire q_a2_s2;
    wire q_a2_s3;
    wire q_a2_s4;
    wire q_a2_s5;
    wire p_a3_s1;
    wire p_a3_s2;
    wire p_a3_s3;
    wire p_a3_s4;
    wire p_a3_s5;
    wire p_a3_s6;
    wire p_a3_s7;
    wire q_a3_s1;
    wire q_a3_s2;
    wire q_a3_s3;
    wire q_a3_s4;
    wire q_a3_s5;
    wire q_a3_s6;
    wire q_a3_s7;
    wire p_b0_s1;
    wire q_b0_s1;
    wire p_b1_s1;
    wire p_b1_s2;
    wire p_b1_s3;
    wire q_b1_s1;
    wire q_b1_s2;
    wire q_b1_s3;
    wire p_b2_s1;
    wire p_b2_s2;
    wire p_b2_s3;
    wire p_b2_s4;
    wire p_b2_s5;
    wire q_b2_s1;
    wire q_b2_s2;
    wire q_b2_s3;
    wire q_b2_s4;
    wire q_b2_s5;
    wire p_b3_s1;
    wire p_b3_s2;
    wire p_b3_s3;
    wire p_b3_s4;
    wire p_b3_s5;
    wire p_b3_s6;
    wire p_b3_s7;
    wire q_b3_s1;
    wire q_b3_s2;
    wire q_b3_s3;
    wire q_b3_s4;
    wire q_b3_s5;
    wire q_b3_s6;
    wire q_b3_s7;
    wire x0;
    wire nx0;
    wire c0_ts;
    wire c0_fs;
    wire c1_f;
    wire c1_t;
    wire x1;
    wire nx1;
    wire c1_ts;
    wire c1_fs;
    wire c2_f;
    wire c2_t;
    wire x2;
    wire nx2;
    wire c2_ts;
    wire c2_fs;
    wire c3_f;
    wire c3_t;
    wire x3;
    wire nx3;
    wire c3_ts;
    wire c3_fs;

    lsdl_inv_x1 U_pa0_s1 (.CLK(c1), .A(a[0]), .OUT(p_a0_s1));  // stage 1
    lsdl_inv_x1 U_qa0_s1 (.CLK(c1), .A(an[0]), .OUT(q_a0_s1));  // stage 1
    lsdl_inv_x1 U_pa1_s1 (.CLK(c1), .A(a[1]), .OUT(p_a1_s1));  // stage 1
    lsdl_inv_x1 U_pa1_s2 (.CLK(c2), .A(p_a1_s1), .OUT(p_a1_s2));  // stage 2
    lsdl_inv_x1 U_pa1_s3 (.CLK(c1), .A(p_a1_s2), .OUT(p_a1_s3));  // stage 3
    lsdl_inv_x1 U_qa1_s1 (.CLK(c1), .A(an[1]), .OUT(q_a1_s1));  // stage 1
    lsdl_inv_x1 U_qa1_s2 (.CLK(c2), .A(q_a1_s1), .OUT(q_a1_s2));  // stage 2
    lsdl_inv_x1 U_qa1_s3 (.CLK(c1), .A(q_a1_s2), .OUT(q_a1_s3));  // stage 3
    lsdl_inv_x1 U_pa2_s1 (.CLK(c1), .A(a[2]), .OUT(p_a2_s1));  // stage 1
    lsdl_inv_x1 U_pa2_s2 (.CLK(c2), .A(p_a2_s1), .OUT(p_a2_s2));  // stage 2
    lsdl_inv_x1 U_pa2_s3 (.CLK(c1), .A(p_a2_s2), .OUT(p_a2_s3));  // stage 3
    lsdl_inv_x1 U_pa2_s4 (.CLK(c2), .A(p_a2_s3), .OUT(p_a2_s4));  // stage 4
    lsdl_inv_x1 U_pa2_s5 (.CLK(c1), .A(p_a2_s4), .OUT(p_a2_s5));  // stage 5
    lsdl_inv_x1 U_qa2_s1 (.CLK(c1), .A(an[2]), .OUT(q_a2_s1));  // stage 1
    lsdl_inv_x1 U_qa2_s2 (.CLK(c2), .A(q_a2_s1), .OUT(q_a2_s2));  // stage 2
    lsdl_inv_x1 U_qa2_s3 (.CLK(c1), .A(q_a2_s2), .OUT(q_a2_s3));  // stage 3
    lsdl_inv_x1 U_qa2_s4 (.CLK(c2), .A(q_a2_s3), .OUT(q_a2_s4));  // stage 4
    lsdl_inv_x1 U_qa2_s5 (.CLK(c1), .A(q_a2_s4), .OUT(q_a2_s5));  // stage 5
    lsdl_inv_x1 U_pa3_s1 (.CLK(c1), .A(a[3]), .OUT(p_a3_s1));  // stage 1
    lsdl_inv_x1 U_pa3_s2 (.CLK(c2), .A(p_a3_s1), .OUT(p_a3_s2));  // stage 2
    lsdl_inv_x1 U_pa3_s3 (.CLK(c1), .A(p_a3_s2), .OUT(p_a3_s3));  // stage 3
    lsdl_inv_x1 U_pa3_s4 (.CLK(c2), .A(p_a3_s3), .OUT(p_a3_s4));  // stage 4
    lsdl_inv_x1 U_pa3_s5 (.CLK(c1), .A(p_a3_s4), .OUT(p_a3_s5));  // stage 5
    lsdl_inv_x1 U_pa3_s6 (.CLK(c2), .A(p_a3_s5), .OUT(p_a3_s6));  // stage 6
    lsdl_inv_x1 U_pa3_s7 (.CLK(c1), .A(p_a3_s6), .OUT(p_a3_s7));  // stage 7
    lsdl_inv_x1 U_qa3_s1 (.CLK(c1), .A(an[3]), .OUT(q_a3_s1));  // stage 1
    lsdl_inv_x1 U_qa3_s2 (.CLK(c2), .A(q_a3_s1), .OUT(q_a3_s2));  // stage 2
    lsdl_inv_x1 U_qa3_s3 (.CLK(c1), .A(q_a3_s2), .OUT(q_a3_s3));  // stage 3
    lsdl_inv_x1 U_qa3_s4 (.CLK(c2), .A(q_a3_s3), .OUT(q_a3_s4));  // stage 4
    lsdl_inv_x1 U_qa3_s5 (.CLK(c1), .A(q_a3_s4), .OUT(q_a3_s5));  // stage 5
    lsdl_inv_x1 U_qa3_s6 (.CLK(c2), .A(q_a3_s5), .OUT(q_a3_s6));  // stage 6
    lsdl_inv_x1 U_qa3_s7 (.CLK(c1), .A(q_a3_s6), .OUT(q_a3_s7));  // stage 7
    lsdl_inv_x1 U_pb0_s1 (.CLK(c1), .A(b[0]), .OUT(p_b0_s1));  // stage 1
    lsdl_inv_x1 U_qb0_s1 (.CLK(c1), .A(bn[0]), .OUT(q_b0_s1));  // stage 1
    lsdl_inv_x1 U_pb1_s1 (.CLK(c1), .A(b[1]), .OUT(p_b1_s1));  // stage 1
    lsdl_inv_x1 U_pb1_s2 (.CLK(c2), .A(p_b1_s1), .OUT(p_b1_s2));  // stage 2
    lsdl_inv_x1 U_pb1_s3 (.CLK(c1), .A(p_b1_s2), .OUT(p_b1_s3));  // stage 3
    lsdl_inv_x1 U_qb1_s1 (.CLK(c1), .A(bn[1]), .OUT(q_b1_s1));  // stage 1
    lsdl_inv_x1 U_qb1_s2 (.CLK(c2), .A(q_b1_s1), .OUT(q_b1_s2));  // stage 2
    lsdl_inv_x1 U_qb1_s3 (.CLK(c1), .A(q_b1_s2), .OUT(q_b1_s3));  // stage 3
    lsdl_inv_x1 U_pb2_s1 (.CLK(c1), .A(b[2]), .OUT(p_b2_s1));  // stage 1
    lsdl_inv_x1 U_pb2_s2 (.CLK(c2), .A(p_b2_s1), .OUT(p_b2_s2));  // stage 2
    lsdl_inv_x1 U_pb2_s3 (.CLK(c1), .A(p_b2_s2), .OUT(p_b2_s3));  // stage 3
    lsdl_inv_x1 U_pb2_s4 (.CLK(c2), .A(p_b2_s3), .OUT(p_b2_s4));  // stage 4
    lsdl_inv_x1 U_pb2_s5 (.CLK(c1), .A(p_b2_s4), .OUT(p_b2_s5));  // stage 5
    lsdl_inv_x1 U_qb2_s1 (.CLK(c1), .A(bn[2]), .OUT(q_b2_s1));  // stage 1
    lsdl_inv_x1 U_qb2_s2 (.CLK(c2), .A(q_b2_s1), .OUT(q_b2_s2));  // stage 2
    lsdl_inv_x1 U_qb2_s3 (.CLK(c1), .A(q_b2_s2), .OUT(q_b2_s3));  // stage 3
    lsdl_inv_x1 U_qb2_s4 (.CLK(c2), .A(q_b2_s3), .OUT(q_b2_s4));  // stage 4
    lsdl_inv_x1 U_qb2_s5 (.CLK(c1), .A(q_b2_s4), .OUT(q_b2_s5));  // stage 5
    lsdl_inv_x1 U_pb3_s1 (.CLK(c1), .A(b[3]), .OUT(p_b3_s1));  // stage 1
    lsdl_inv_x1 U_pb3_s2 (.CLK(c2), .A(p_b3_s1), .OUT(p_b3_s2));  // stage 2
    lsdl_inv_x1 U_pb3_s3 (.CLK(c1), .A(p_b3_s2), .OUT(p_b3_s3));  // stage 3
    lsdl_inv_x1 U_pb3_s4 (.CLK(c2), .A(p_b3_s3), .OUT(p_b3_s4));  // stage 4
    lsdl_inv_x1 U_pb3_s5 (.CLK(c1), .A(p_b3_s4), .OUT(p_b3_s5));  // stage 5
    lsdl_inv_x1 U_pb3_s6 (.CLK(c2), .A(p_b3_s5), .OUT(p_b3_s6));  // stage 6
    lsdl_inv_x1 U_pb3_s7 (.CLK(c1), .A(p_b3_s6), .OUT(p_b3_s7));  // stage 7
    lsdl_inv_x1 U_qb3_s1 (.CLK(c1), .A(bn[3]), .OUT(q_b3_s1));  // stage 1
    lsdl_inv_x1 U_qb3_s2 (.CLK(c2), .A(q_b3_s1), .OUT(q_b3_s2));  // stage 2
    lsdl_inv_x1 U_qb3_s3 (.CLK(c1), .A(q_b3_s2), .OUT(q_b3_s3));  // stage 3
    lsdl_inv_x1 U_qb3_s4 (.CLK(c2), .A(q_b3_s3), .OUT(q_b3_s4));  // stage 4
    lsdl_inv_x1 U_qb3_s5 (.CLK(c1), .A(q_b3_s4), .OUT(q_b3_s5));  // stage 5
    lsdl_inv_x1 U_qb3_s6 (.CLK(c2), .A(q_b3_s5), .OUT(q_b3_s6));  // stage 6
    lsdl_inv_x1 U_qb3_s7 (.CLK(c1), .A(q_b3_s6), .OUT(q_b3_s7));  // stage 7
    lsdl_aoi22_x1 U_x0 (.CLK(c1), .A1(a[0]), .A2(b[0]), .B1(an[0]), .B2(bn[0]), .OUT(x0));  // stage 1
    lsdl_aoi22_x1 U_nx0 (.CLK(c1), .A1(a[0]), .A2(bn[0]), .B1(an[0]), .B2(b[0]), .OUT(nx0));  // stage 1
    lsdl_inv_x1 U_cst0 (.CLK(c1), .A(cinn), .OUT(c0_ts));  // stage 1
    lsdl_inv_x1 U_csf0 (.CLK(c1), .A(cin), .OUT(c0_fs));  // stage 1
    lsdl_aoi22_x1 U_coF0 (.CLK(c2), .A1(q_a0_s1), .A2(q_b0_s1), .B1(c0_ts), .B2(x0), .OUT(c1_f));  // stage 2
    lsdl_aoi22_x1 U_coT0 (.CLK(c2), .A1(p_a0_s1), .A2(p_b0_s1), .B1(c0_fs), .B2(x0), .OUT(c1_t));  // stage 2
    lsdl_aoi22_x1 U_s0 (.CLK(c2), .A1(x0), .A2(c0_ts), .B1(nx0), .B2(c0_fs), .OUT(sum[0]));  // stage 2
    lsdl_aoi22_x1 U_x1 (.CLK(c1), .A1(p_a1_s2), .A2(p_b1_s2), .B1(q_a1_s2), .B2(q_b1_s2), .OUT(x1));  // stage 3
    lsdl_aoi22_x1 U_nx1 (.CLK(c1), .A1(p_a1_s2), .A2(q_b1_s2), .B1(q_a1_s2), .B2(p_b1_s2), .OUT(nx1));  // stage 3
    lsdl_inv_x1 U_cst1 (.CLK(c1), .A(c1_f), .OUT(c1_ts));  // stage 3
    lsdl_inv_x1 U_csf1 (.CLK(c1), .A(c1_t), .OUT(c1_fs));  // stage 3
    lsdl_aoi22_x1 U_coF1 (.CLK(c2), .A1(q_a1_s3), .A2(q_b1_s3), .B1(c1_ts), .B2(x1), .OUT(c2_f));  // stage 4
    lsdl_aoi22_x1 U_coT1 (.CLK(c2), .A1(p_a1_s3), .A2(p_b1_s3), .B1(c1_fs), .B2(x1), .OUT(c2_t));  // stage 4
    lsdl_aoi22_x1 U_s1 (.CLK(c2), .A1(x1), .A2(c1_ts), .B1(nx1), .B2(c1_fs), .OUT(sum[1]));  // stage 4
    lsdl_aoi22_x1 U_x2 (.CLK(c1), .A1(p_a2_s4), .A2(p_b2_s4), .B1(q_a2_s4), .B2(q_b2_s4), .OUT(x2));  // stage 5
    lsdl_aoi22_x1 U_nx2 (.CLK(c1), .A1(p_a2_s4), .A2(q_b2_s4), .B1(q_a2_s4), .B2(p_b2_s4), .OUT(nx2));  // stage 5
    lsdl_inv_x1 U_cst2 (.CLK(c1), .A(c2_f), .OUT(c2_ts));  // stage 5
    lsdl_inv_x1 U_csf2 (.CLK(c1), .A(c2_t), .OUT(c2_fs));  // stage 5
    lsdl_aoi22_x1 U_coF2 (.CLK(c2), .A1(q_a2_s5), .A2(q_b2_s5), .B1(c2_ts), .B2(x2), .OUT(c3_f));  // stage 6
    lsdl_aoi22_x1 U_coT2 (.CLK(c2), .A1(p_a2_s5), .A2(p_b2_s5), .B1(c2_fs), .B2(x2), .OUT(c3_t));  // stage 6
    lsdl_aoi22_x1 U_s2 (.CLK(c2), .A1(x2), .A2(c2_ts), .B1(nx2), .B2(c2_fs), .OUT(sum[2]));  // stage 6
    lsdl_aoi22_x1 U_x3 (.CLK(c1), .A1(p_a3_s6), .A2(p_b3_s6), .B1(q_a3_s6), .B2(q_b3_s6), .OUT(x3));  // stage 7
    lsdl_aoi22_x1 U_nx3 (.CLK(c1), .A1(p_a3_s6), .A2(q_b3_s6), .B1(q_a3_s6), .B2(p_b3_s6), .OUT(nx3));  // stage 7
    lsdl_inv_x1 U_cst3 (.CLK(c1), .A(c3_f), .OUT(c3_ts));  // stage 7
    lsdl_inv_x1 U_csf3 (.CLK(c1), .A(c3_t), .OUT(c3_fs));  // stage 7
    lsdl_aoi22_x1 U_coF3 (.CLK(c2), .A1(q_a3_s7), .A2(q_b3_s7), .B1(c3_ts), .B2(x3), .OUT(coutn));  // stage 8
    lsdl_aoi22_x1 U_coT3 (.CLK(c2), .A1(p_a3_s7), .A2(p_b3_s7), .B1(c3_fs), .B2(x3), .OUT(cout));  // stage 8
    lsdl_aoi22_x1 U_s3 (.CLK(c2), .A1(x3), .A2(c3_ts), .B1(nx3), .B2(c3_fs), .OUT(sum[3]));  // stage 8

endmodule
