#!/usr/bin/env python3
"""gen_cmos_adder.py — matched-architecture CMOS systolic ripple adder.

The static-CMOS counterpart of gen_lsdl_adder.py for the LSDL-vs-CMOS
benchmark comparison. SAME dataflow: systolic (skewed) ripple-carry, carry
advances one bit per clock cycle, outputs time-skewed (sum[i] valid i+1
cycles after its operands — identical cycle latency to the LSDL flavor,
whose 2i+2 half-cycles = i+1 cycles).

Differences from LSDL (the honest CMOS idiom at the same architecture):
  * Single-rail — CMOS inverts freely, no dual-rail tax.
  * One stock full-adder cell (addf_1) per bit replaces the 5-aoi22 dual-rail
    slice; pipeline registers are explicit DFFs (dffq_1) instead of being
    integrated into every gate.
  * One clock, posedge — no two-phase C1/C2.

Structure for width W (stage k = pipeline register rank k):
  * Operand staging: a[i], b[i] each ride a chain of i DFFs, arriving at
    bit i's full adder in cycle i.                      (2 * sum(i) DFFs)
  * FA_i (addf_1): S, CO from staged a_i, b_i and carry c_i.       (W FAs)
  * c_{i+1} = CO registered each cycle (the systolic carry).       (W DFFs)
  * sum[i] = S registered, then straight out (skewed).             (W DFFs)
Cell count: W^2 + W DFFs + W addf  (W=64: 4,160 DFF + 64 addf = 4,224).

Usage:
    gen_cmos_adder.py --width 64 --selftest --out adder64_cmos.v
"""

from __future__ import annotations
import argparse
import random
import sys

DFF = 'gf180mcu_fd_sc_mcu9t5v0__dffq_1'    # CLK, D -> Q
ADDF = 'gf180mcu_fd_sc_mcu9t5v0__addf_1'   # A, B, CI -> S, CO


class Netlist:
    def __init__(self, width: int):
        self.w = width
        self.wires: list[str] = []
        self.dffs: list[tuple] = []   # (name, d, q)
        self.fas: list[tuple] = []    # (name, a, b, ci, s, co)

    def wire(self, name: str) -> str:
        self.wires.append(name)
        return name

    def dff(self, name: str, d: str, q: str) -> str:
        self.dffs.append((name, d, q))
        return q

    def fa(self, name: str, a: str, b: str, ci: str, s: str, co: str):
        self.fas.append((name, a, b, ci, s, co))


def build(width: int) -> Netlist:
    nl = Netlist(width)
    w = width

    # operand staging chains: bit i delayed i cycles
    staged: dict[tuple, str] = {}
    for op in ('a', 'b'):
        for i in range(w):
            prev = f'{op}[{i}]'
            for k in range(1, i + 1):
                net = nl.wire(f'{op}{i}_s{k}')
                nl.dff(f'U_{op}{i}_s{k}', prev, net)
                prev = net
            staged[(op, i)] = prev   # arrives at cycle i

    carry = 'cin'   # carry into bit 0, cycle 0
    for i in range(w):
        s_net = nl.wire(f's{i}')
        co_net = nl.wire(f'co{i}')
        nl.fa(f'U_fa{i}', staged[('a', i)], staged[('b', i)], carry,
              s_net, co_net)
        # register sum (skewed output) and carry (to bit i+1, next cycle)
        nl.dff(f'U_sq{i}', s_net, f'sum[{i}]')
        if i == w - 1:
            nl.dff(f'U_cq{i}', co_net, 'cout')
        else:
            carry = nl.dff(f'U_cq{i}', co_net, nl.wire(f'c{i + 1}'))
    return nl


def emit_verilog(nl: Netlist) -> str:
    w = nl.w
    lines = [
        f'// cmos_adder{w} — {w}-bit systolic ripple adder, static CMOS',
        f'// (gf180mcu_fd_sc_mcu9t5v0). Architecture-matched to lsdl_adder{w}:',
        f'// carry advances 1 bit/cycle; sum[i] valid at cycle i+1 (skewed).',
        f'// Generated by gen_cmos_adder.py — do not edit.',
        f'// Cells: {len(nl.dffs)} dffq_1 + {len(nl.fas)} addf_1',
        f'`timescale 1ns/1ps',
        f'module cmos_adder{w} (',
        f'    input  clk,',
        f'    input  [{w - 1}:0] a,',
        f'    input  [{w - 1}:0] b,',
        f'    input  cin,',
        f'    output [{w - 1}:0] sum,',
        f'    output cout',
        f');',
        '',
    ]
    for wn in nl.wires:
        lines.append(f'    wire {wn};')
    lines.append('')
    for name, d, q in nl.dffs:
        lines.append(f'    {DFF} {name} (.CLK(clk), .D({d}), .Q({q}));')
    lines.append('')
    for name, a, b, ci, s, co in nl.fas:
        lines.append(f'    {ADDF} {name} (.A({a}), .B({b}), .CI({ci}), '
                     f'.S({s}), .CO({co}));')
    lines += ['', 'endmodule', '']
    return '\n'.join(lines)


def selftest(nl: Netlist, vectors: int = 200) -> bool:
    """Cycle-accurate check: combinational FAs settle from current register
    values, then all DFFs clock simultaneously. Inputs held constant; the
    pipeline settles to the steady-state result."""
    w = nl.w
    rng = random.Random(42)
    ticks = w + 4
    ok = True
    for _ in range(vectors):
        a = rng.getrandbits(w)
        b = rng.getrandbits(w)
        ci = rng.getrandbits(1)
        val: dict[str, int] = {'cin': ci}
        for i in range(w):
            val[f'a[{i}]'] = (a >> i) & 1
            val[f'b[{i}]'] = (b >> i) & 1
        for _, _, q in nl.dffs:
            val.setdefault(q, 0)
        for _ in range(ticks):
            # combinational pass (FAs depend only on reg outputs / ports)
            for _, fa_a, fa_b, fa_ci, s, co in nl.fas:
                t = val[fa_a] + val[fa_b] + val[fa_ci]
                val[s], val[co] = t & 1, t >> 1
            # simultaneous register update
            nxt = dict(val)
            for _, d, q in nl.dffs:
                nxt[q] = val[d]
            val = nxt
        got = sum(val[f'sum[{i}]'] << i for i in range(w))
        exp = a + b + ci
        if got != (exp & ((1 << w) - 1)) or val['cout'] != exp >> w:
            print(f'FAIL a={a:#x} b={b:#x} cin={ci}: got sum={got:#x} '
                  f'cout={val["cout"]}')
            ok = False
    return ok


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument('--width', type=int, default=64)
    ap.add_argument('--out')
    ap.add_argument('--selftest', action='store_true')
    args = ap.parse_args()

    nl = build(args.width)
    area = len(nl.dffs) * 15.68 * 5.04 + len(nl.fas) * 16.80 * 5.04
    print(f'cmos_adder{args.width}: {len(nl.dffs)} dffq_1 + '
          f'{len(nl.fas)} addf_1 = {len(nl.dffs) + len(nl.fas)} cells, '
          f'{area / 1e6:.3f} mm2 cell area, '
          f'sum[{args.width - 1}] latency {args.width} cycles')

    if args.selftest:
        if selftest(nl):
            print(f'SELFTEST PASS (200 random vectors, width {args.width})')
        else:
            print('SELFTEST FAIL')
            return 1
    if args.out:
        with open(args.out, 'w') as f:
            f.write(emit_verilog(nl))
        print(f'wrote {args.out}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
