#!/usr/bin/env python3
"""gen_vectors.py — 10 test vectors + expected sums for the adder testers.

Emits vectors.vh with localparam arrays consumed by adder_tester.v.
Both adders (lsdl_adder64, cmos_adder64) compute sum = a + b + cin, so a
single vector ROM serves the identical tester pair.

Vector selection: carry-ripple worst cases + zero + 5 PRNG vectors.
"""

import random

W = 64
M = (1 << W) - 1

rng = random.Random(2026)

vecs = [
    (M, 1, 0),              # full carry ripple: FFFF..FF + 1
    (0xAAAAAAAAAAAAAAAA, 0x5555555555555555, 1),     # alternating + cin
    (M, M, 1),              # max + max + 1
    (0, 0, 0),              # zero
    (M >> 1, M >> 1, 1),    # ripple to MSB
]
vecs += [(rng.getrandbits(W), rng.getrandbits(W), rng.getrandbits(1))
         for _ in range(5)]

lines = [
    '// vectors.vh — generated by gen_vectors.py. Do not edit.',
    f'localparam integer N_VEC = {len(vecs)};',
]
for sig, idx in (('A', 0), ('B', 1), ('CIN', 2)):
    for i, v in enumerate(vecs):
        if idx < 2:
            lines.append(f"localparam [63:0] {sig}{i} = 64'h{v[idx]:016x};")
        else:
            lines.append(f"localparam {sig}{i} = 1'b{v[2]};")
for i, (a, b, ci) in enumerate(vecs):
    s = a + b + ci
    lines.append(f"localparam [64:0] EXP{i} = 65'h{s:017x};")

with open(__file__.replace('gen_vectors.py', 'vectors.vh'), 'w') as f:
    f.write('\n'.join(lines) + '\n')
print(f'wrote vectors.vh ({len(vecs)} vectors)')
for i, (a, b, ci) in enumerate(vecs):
    print(f'  {i}: {a:016x} + {b:016x} + {ci} = {(a + b + ci):017x}')
