// Auto-generated by LibreLane
module adder_tester(
`ifdef USE_POWER_PINS
  inout VDD,
  inout VSS,
`endif
  input c1,
  input c2,
  input[64:0] result,
  output[63:0] a,
  output[63:0] b,
  output cin,
  output correct,
  output incorrect
);
endmodule
